// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp1kJNRwBI8tdE0lXGbYTM94mZRl1X0Ao',
    appId: '1:334442491394:web:2f70eecb2538e0e1eb411b',
    messagingSenderId: '334442491394',
    projectId: 'kitapistan-d320b',
    authDomain: 'kitapistan-d320b.firebaseapp.com',
    databaseURL:
        'https://kitapistan-d320b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kitapistan-d320b.appspot.com',
    measurementId: 'G-5TRW8LL46G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC6qkSGxHwmSkQr8QGuhK3LfSyU10VrzU',
    appId: '1:334442491394:android:c64d39497a5c9178eb411b',
    messagingSenderId: '334442491394',
    projectId: 'kitapistan-d320b',
    databaseURL:
        'https://kitapistan-d320b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kitapistan-d320b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpcFCC1btwq6o0gc1dyjmQJsKcEJgYSMA',
    appId: '1:334442491394:ios:9048da25fe058b1feb411b',
    messagingSenderId: '334442491394',
    projectId: 'kitapistan-d320b',
    databaseURL:
        'https://kitapistan-d320b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kitapistan-d320b.appspot.com',
    iosBundleId: 'com.example.kitapistan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpcFCC1btwq6o0gc1dyjmQJsKcEJgYSMA',
    appId: '1:334442491394:ios:0ba3c0c997740f5deb411b',
    messagingSenderId: '334442491394',
    projectId: 'kitapistan-d320b',
    databaseURL:
        'https://kitapistan-d320b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kitapistan-d320b.appspot.com',
    iosBundleId: 'com.example.kitapistan.RunnerTests',
  );
}
